In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
a.size

3

In [9]:
a.itemsize

8

In [11]:
a[0]

1

In [12]:
a*10

array([10, 20, 30])

In [13]:
#Differences between list and array

In [14]:
l = [1,2,3]

In [15]:
a = np.array(l)

In [16]:
l.append(4)

In [17]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [18]:
l = l + [4]

In [19]:
l

[1, 2, 3, 4, 4]

In [20]:
a = a + np.array(4)

In [21]:
a

array([5, 6, 7])

In [22]:
l = l *2

In [23]:
l

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [24]:
a = a * 2

In [25]:
a

array([10, 12, 14])

In [26]:
a = np.sqrt(a)

In [27]:
a

array([3.16227766, 3.46410162, 3.74165739])

In [28]:
a = np.log(a)

In [29]:
a

array([1.15129255, 1.24245332, 1.31952866])

In [30]:
#dot product

In [31]:
l

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [32]:
l1 = [1,2,3]
l2 = [3,4,5]

In [33]:
dot  = 0
for i in  range(len(l1)):
    dot = dot + l1[i]*l2[i]
print(dot)

26


In [34]:
a1 = np.array(l1)
a2 = np.array(l2)

In [35]:
dot = np.dot(a1,a2)

In [36]:
dot

26

In [38]:
prod = a1 * a2
np.sum(prod)

26

In [39]:
(a1*a2).sum()

26

In [40]:
dot = a1@a2

In [41]:
dot

26

In [11]:
from timeit import default_timer as timer

In [12]:
a = np.random.randn(1000)

In [13]:
a.shape

(1000,)

In [14]:
b = np.random.randn(1000)

In [15]:
A = list(a)

In [16]:
B= list(b)

In [17]:
def dot_list():
    dot  = 0
    for i in  range(len(A)):
        dot = dot + A[i]*B[i]
#     return dot 
#     print(dot)

In [18]:
def dot_array():
    np.dot(a,b)

In [19]:
T= 1000
start= timer()
for i in range(T):
    dot_list()
end = timer()
time_list = end-start
time_list

0.08215815599942289

In [20]:
T= 1000
start= timer()
for i in range(T):
    dot_array()
end = timer()
time_array = end-start
time_array

0.0011916410003323108

In [22]:
time_list/time_array

68.94539209083239

In [23]:
#Multi dimensional arays

In [24]:
a = np.array([1,2])

In [25]:
a.shape

(2,)

In [26]:
a = np.array([[1,2], [3,4]])

In [27]:
a.shape

(2, 2)

In [28]:
a[0]

array([1, 2])

In [29]:
a[0][0]

1

In [30]:
a[0,0]

1

In [32]:
a

array([[1, 2],
       [3, 4]])

In [31]:
a[:,0]

array([1, 3])

In [33]:
a.T

array([[1, 3],
       [2, 4]])

In [34]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
#slicing

In [36]:
a[0,:]

array([1, 2])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a[-1,-1]

4

In [39]:
a[-1, -2]

3

In [40]:
#Boolean indexing

In [42]:
a = np.array([[1,2], [3,4], [5,6]])

In [43]:
bool_a = a>2
bool_a

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [44]:
a[bool_a]

array([3, 4, 5, 6])

In [46]:
#we want same size
np.where(a>2, a, "False")

array([['False', 'False'],
       ['3', '4'],
       ['5', '6']], dtype='<U21')

In [47]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
#fancy indexing
a = np.array([10, 23,45,56,78,89,])

In [49]:
b = [1,3,5]

In [50]:
a[b]

array([23, 56, 89])

In [51]:
#filter