In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
a.size

3

In [9]:
a.itemsize

8

In [11]:
a[0]

1

In [12]:
a*10

array([10, 20, 30])

In [13]:
#Differences between list and array

In [14]:
l = [1,2,3]

In [15]:
a = np.array(l)

In [16]:
l.append(4)

In [17]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [18]:
l = l + [4]

In [19]:
l

[1, 2, 3, 4, 4]

In [20]:
a = a + np.array(4)

In [21]:
a

array([5, 6, 7])

In [22]:
l = l *2

In [23]:
l

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [24]:
a = a * 2

In [25]:
a

array([10, 12, 14])

In [26]:
a = np.sqrt(a)

In [27]:
a

array([3.16227766, 3.46410162, 3.74165739])

In [28]:
a = np.log(a)

In [29]:
a

array([1.15129255, 1.24245332, 1.31952866])

In [30]:
#dot product

In [31]:
l

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [32]:
l1 = [1,2,3]
l2 = [3,4,5]

In [33]:
dot  = 0
for i in  range(len(l1)):
    dot = dot + l1[i]*l2[i]
print(dot)

26


In [34]:
a1 = np.array(l1)
a2 = np.array(l2)

In [35]:
dot = np.dot(a1,a2)

In [36]:
dot

26

In [38]:
prod = a1 * a2
np.sum(prod)

26

In [39]:
(a1*a2).sum()

26

In [40]:
dot = a1@a2

In [41]:
dot

26

In [11]:
from timeit import default_timer as timer

In [12]:
a = np.random.randn(1000)

In [13]:
a.shape

(1000,)

In [14]:
b = np.random.randn(1000)

In [15]:
A = list(a)

In [16]:
B= list(b)

In [17]:
def dot_list():
    dot  = 0
    for i in  range(len(A)):
        dot = dot + A[i]*B[i]
#     return dot 
#     print(dot)

In [18]:
def dot_array():
    np.dot(a,b)

In [19]:
T= 1000
start= timer()
for i in range(T):
    dot_list()
end = timer()
time_list = end-start
time_list

0.08215815599942289

In [20]:
T= 1000
start= timer()
for i in range(T):
    dot_array()
end = timer()
time_array = end-start
time_array

0.0011916410003323108

In [22]:
time_list/time_array

68.94539209083239

In [23]:
#Multi dimensional arays

In [24]:
a = np.array([1,2])

In [25]:
a.shape

(2,)

In [26]:
a = np.array([[1,2], [3,4]])

In [27]:
a.shape

(2, 2)

In [28]:
a[0]

array([1, 2])

In [29]:
a[0][0]

1

In [30]:
a[0,0]

1

In [32]:
a

array([[1, 2],
       [3, 4]])

In [31]:
a[:,0]

array([1, 3])

In [33]:
a.T

array([[1, 3],
       [2, 4]])

In [34]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
#slicing

In [36]:
a[0,:]

array([1, 2])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a[-1,-1]

4

In [39]:
a[-1, -2]

3

In [40]:
#Boolean indexing

In [42]:
a = np.array([[1,2], [3,4], [5,6]])

In [43]:
bool_a = a>2
bool_a

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [44]:
a[bool_a]

array([3, 4, 5, 6])

In [46]:
#we want same size
np.where(a>2, a, "False")

array([['False', 'False'],
       ['3', '4'],
       ['5', '6']], dtype='<U21')

In [47]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
#fancy indexing
a = np.array([10, 23,45,56,78,89,])

In [49]:
b = [1,3,5]

In [50]:
a[b]

array([23, 56, 89])

In [51]:
#filter 

In [7]:
a = np.array([1,2,3, 4,5,6,7,8,9,10])

In [5]:
even = np.argwhere(a%2==0).flatten()

In [6]:
even

array([1, 3, 5, 7, 9])

In [8]:
#reshape

In [9]:
a.shape

(10,)

In [15]:
c = a.reshape((5,2))

In [16]:
c.shape

(5, 2)

In [17]:
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
b = a[np.newaxis,:]

In [19]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [20]:
b.shape

(1, 10)

In [21]:
c = a[:, np.newaxis]

In [22]:
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [23]:
#concatenation

In [24]:
a = np.array([[1,2], [3,4]] )

In [28]:
a.shape

(2, 2)

In [31]:
b = np.array([[5,6]])

In [32]:
b.shape

(1, 2)

In [36]:
c = np.concatenate((a,b.T), axis=1)

In [37]:
c

array([[1, 2, 5],
       [3, 4, 6]])

In [38]:
#hstack and vstack

In [47]:
a = np.array([[1,2,3,4]])

In [48]:
b = np.array([[5,6,7,8]])

In [49]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [43]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
x = np.array([[1,2,3], [4,5,6] ] )

In [52]:
a = np.array([1,0,1])

In [53]:
x + a

array([[2, 2, 4],
       [5, 5, 7]])

In [54]:
#data science functions

In [55]:
a = np.array([[7,8,9,10,11,12], [13,14,15,16,17,18]])

In [56]:
a

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [57]:
a.sum(axis=None)

150

In [58]:
a.sum(axis=0)

array([20, 22, 24, 26, 28, 30])

In [60]:
a.sum(axis=1)

array([57, 93])

In [61]:
a.mean(axis=0)

array([10., 11., 12., 13., 14., 15.])

In [62]:
a.min(axis=0)

array([ 7,  8,  9, 10, 11, 12])

In [64]:
a.std(axis=0)

array([3., 3., 3., 3., 3., 3.])

In [65]:
np.std(a,axis=0)

array([3., 3., 3., 3., 3., 3.])

In [66]:
a.mean()

12.5

In [67]:
#data types

In [68]:
x = np.array([1,2])

In [69]:
x.dtype

dtype('int64')

In [74]:
x = np.array([1,2], dtype=np.float64)

In [75]:
x.dtype

dtype('float64')

In [76]:
x

array([1., 2.])

In [77]:
#generting arrays

In [78]:
a = np.zeros((2,3))

In [79]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.full((2,3),  5)

array([[5, 5, 5],
       [5, 5, 5]])

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
start =0
stop =10
num_steps = 20
b = np.linspace(start, stop, num_steps)

In [88]:
b.shape

(20,)

In [89]:
b.reshape(5, 4)

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737],
       [ 2.10526316,  2.63157895,  3.15789474,  3.68421053],
       [ 4.21052632,  4.73684211,  5.26315789,  5.78947368],
       [ 6.31578947,  6.84210526,  7.36842105,  7.89473684],
       [ 8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [90]:
#raandom 

In [91]:
a = np.random.random((3,2))   #0-1 uniform distrbution
a

array([[0.3857851 , 0.80892407],
       [0.10248082, 0.7304782 ],
       [0.5707825 , 0.32492867]])

In [94]:
np.random.randn(3,2) #normal distribution

array([[ 0.08885471, -0.23194681],
       [ 2.87463325,  1.33150062],
       [ 1.35175709, -0.9639364 ]])

In [98]:
np.random.choice(5,size=10)

array([2, 4, 4, 4, 3, 3, 3, 3, 4, 1])

In [99]:
#linalg

In [101]:
a = np.array([[1,1], [1.5,4]])

In [102]:
b = np.array([2200, 5050])

In [105]:
x = np.linalg.inv(a).dot(b)

In [106]:
x

array([1500.,  700.])

In [107]:
np.linalg.solve(a,b)

array([1500.,  700.])

In [108]:
#loadtxt, genfromtxt

In [ ]:
np.loadtxt("filename.csv", delimiter="," dtpe=np.float32)